### PR TITLE
[ApolloPagination] Design document that details the architecture of `GraphQLQueryPager`

### PR DESCRIPTION
**Pull request by Iron-Ham**
This document details the design decisions made thus far, using the state of the pager in [this pull request](https://github.com/apollographql/apollo-ios-dev/pull/115). 

___

This pull request introduces a new pagination strategy for the `apollo-ios-pagination` library. The main changes are in the `apollo-ios-pagination/Design.md` file, where the new class `GraphQLQueryPager` is described in detail. This class is responsible for handling the logic of fetching new pages and exposing APIs for interacting with the pager. The class is designed to be thread-safe, cancellable, flexible, and easy to use. It uses Swift Concurrency APIs and Swift `actor`s to ensure thread-safety and serialize calls. The pull request also includes a detailed explanation of the design principles, goals, and consequences of the new pagination API, as well as alternatives considered and recommended reading. 

Key Changes:

* The pull request includes a detailed explanation of the design principles, goals, and consequences of the new pagination API. It also includes alternatives considered and recommended reading.

### CODE REVIEW

**Review by AnthonyMDev — APPROVED** [review]
This is incredibly detailed! I think that we should move this into just the dev repo, rather than including it with the pagination package. One of the main goals with the dev repo was to remove as many non-source files from the module repos as possible.

So can we change the path for this file to `apollo-ios-dev/docs/DesignNotes/apollo-ios-pagination.md`

**Comment by Iron-Ham** [comment]
Sounds like a plan. Should I re-structure the usage-centric `README.md` in https://github.com/apollographql/apollo-ios-dev/pull/182 into a doc in the dev repo as well?

**Comment by AnthonyMDev** [comment]
> Should I re-structure the usage-centric README.md in https://github.com/apollographql/apollo-ios-dev/pull/182 into a doc in the dev repo as well?

I haven't looked at that PR yet, but I think that the README should follow the pattern of the README in `apollo-ios` and `apollo-ios-codegen`. It has very basic needed information about the package, but all of the usage-centric stuff should be in docs pages on our docs site. The README can have a **Usage** or **Getting Started** section that _links out_ to the actual docs pages. That way we only have to maintain the usage documentation in one place and we keep our repos as small as possible!

**Comment by calvincestari** [comment]
This is fantastic @Iron-Ham, I love the detail and transparency. Very well done! 😍

**Review by calvincestari — APPROVED** [review]

**Comment by Iron-Ham** [comment]
@calvincestari thank you! 
I'm going to make sure to update this after we merge https://github.com/apollographql/apollo-ios-dev/pull/115 so that the naming is up-to-date (`GraphQLQueryPager.Actor` -> `AsyncGraphQLQueryPager`)

**Comment by TechBrotalks** [comment]
@Iron-Ham Please Kindly check this out https://github.com/orgs/community/discussions/81370
I want to know if its feasible

**Pull request closed without merging**
