### PR TITLE
Field Merging[2/x] Compute MergedSelections w/MergingStrategy

### PR DESCRIPTION
**Pull request by AnthonyMDev**
### TL;DR
Updated the logic for merging selections in ComputedSelectionSet.

### What changed?
- Implemented a new MergedSelections logic to handle different merging strategies.

### How to test?
Unit tests will be written before this PR is marked ready for review.

### Why make this change?
To improve the handling of merged selections in ComputedSelectionSet based on different merging strategies.

---

### CODE REVIEW

**Comment by AnthonyMDev** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/apollographql/apollo-ios-dev/307?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#307** <a href="https://app.graphite.dev/github/pr/apollographql/apollo-ios-dev/307?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#306** <a href="https://app.graphite.dev/github/pr/apollographql/apollo-ios-dev/306?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AnthonyMDev and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by tahirmt** [comment]
@AnthonyMDev I ran this branch without field merging and I'm still seeing merged fields. I reproduced it on a sample project for easy review https://github.com/tahirmt/apollo-codegen-demo. Maybe I missed something but I think I got everything set up correctly.

Here `fieldMerging` is set to `none`
https://github.com/tahirmt/apollo-codegen-demo/blob/98b3390ecb0b35e3c4939176656f44442a90aab0/Sources/codegen/Command.swift#L31

And here is the generated query still showing merged fields 
https://github.com/tahirmt/apollo-codegen-demo/blob/98b3390ecb0b35e3c4939176656f44442a90aab0/API/Sources/Operations/Queries/NodeQuery.graphql.swift#L60

Let me know if I missed anything

**Comment by AnthonyMDev** [comment]
I made a very silly oversight yesterday. While the field merging strategies work properly, they are not actually affecting the generated templates yet. I'm going to get that sorted out today and will have another PR up with this working soon!
Sorry for the confusion @tahirmt

**Comment by tahirmt** [comment]
Ah no worries. I was just too excited to try out.

**Comment by AnthonyMDev** [comment]
Closing. This is replaced by #431

**Pull request closed without merging**
