### PR TITLE
Docs Update for Replatform

### PR DESCRIPTION
**Pull request by BlenderDude**

### CODE REVIEW

**Review by calvincestari — COMMENTED** [review]
The changes look correct but I cannot verify that it's all rendered correctly because the docs preview has failed - is that expected?

**Comment by Meschreiber** [comment]
> The changes look correct but I cannot verify that it's all rendered correctly because the docs preview has failed - is that expected?

@BlenderDude said that the preview issue should be non-blocking, but will let him confirm here!

**Review by calvincestari — APPROVED** [review]

**Comment by BlenderDude** [comment]
!docs preview

**Comment by calvincestari** [comment]
@BlenderDude, the [docs deploy action is failing](https://github.com/apollographql/apollo-ios-dev/actions/runs/11355172448/job/31583988431). Not sure what needs to be done there now.

**Pull request merged**
