### PR TITLE
Fix warnings in codegen configuration documentation

### PR DESCRIPTION
**Pull request by mt00chikin**
ApolloCodegenConfiguration's documentation had invalid references, which was causing the GenerateDocumentation command to fail.

```
[DEBUG - ApolloCodegenLib:main.swift:77] - Generating documentation for 'ApolloCodegenLib'...
Converting documentation...
/Users/t201595/src/apollo-ios-dev/apollo-ios-codegen/Sources/ApolloCodegenLib/ApolloCodegenConfiguration.swift:672:59: warning: 'EnumCase' doesn't exist at '/ApolloCodegenLib/ApolloCodegenConfiguration/ConversionStrategies'
/Users/t201595/src/apollo-ios-dev/apollo-ios-codegen/Sources/ApolloCodegenLib/ApolloCodegenConfiguration.swift:698:51: warning: 'CaseConversionStrategy' doesn't exist at '/ApolloCodegenLib/ApolloCodegenConfiguration'
/Users/t201595/src/apollo-ios-dev/apollo-ios-codegen/Sources/ApolloCodegenLib/ApolloCodegenConfiguration.swift:703:50: warning: 'CaseConversionStrategy' doesn't exist at '/ApolloCodegenLib/ApolloCodegenConfiguration'
Conversion complete! (0.29s)
Generated DocC archive at '/Users/t201595/src/apollo-ios-dev/docs/docc/ApolloCodegenLib.doccarchive'
```

The header docs were pointing to EnumCase and were missing an additional path component. This fixes those invalid references and re-generates the documentation.

Current state:
Screenshot 2023-11-07 at 13 59 08
Screenshot 2023-11-07 at 13 59 35

Updated:
Screenshot 2023-11-07 at 14 00 11
Screenshot 2023-11-07 at 14 00 07

### CODE REVIEW

**Review by calvincestari — CHANGES_REQUESTED** [review]
Thanks for fixing these warnings @mt00chikin. There are a lot of documentation changes in here that haven't gone out in a release yet though. The reason for that is the documentation is built as soon as the PR is merged whereas releases are from a tag.

So to fix this:
1. Create a new branch from the `1.7.0` tag,
2. Redo your edits to `ApolloCodegenConfiguration`,
3. Re-generate the documentation

That should include only the fixes to the codegen configuration and not the other stuff we haven't released yet - thanks.

**Comment by calvincestari** [comment]
You'll have to end up force pushing if you keep this branch name or just close this PR and create an entirely new one.

**Comment by mt00chikin** [comment]
No prob. Thanks for the info! I was wondering why the documentation was so different on my branch, that explains it. I'll try to get this updated soon.

**Review by AnthonyMDev — APPROVED** [review]
Thanks so much for this!

**Review by calvincestari — APPROVED** [review]
Thanks for pushing the update @mt00chikin, it's a more concise diff now - thanks.

**Comment by mt00chikin** [comment]
No prob! I saw that a test failed, but I noticed that my change has an invalid reference 🤦 I'm gonna fix it and get one more commit up

**Comment by mt00chikin** [comment]
Or not ;)

**Comment by calvincestari** [comment]
The failed test was in the pagination module though and didn't look related to the docs change. So I merged it anyways.

**Comment by mt00chikin** [comment]
Sounds good. I accidentally left the old CaseConversionStrategy in the path for the EnumCases header doc. 
Was gonna remove that, but I could just make that change in a pull request against `main` and the documentation should eventually pick it up.

**Pull request merged**
