### PR TITLE
chore: Disable `@defer` support

### PR DESCRIPTION
**Pull request by calvincestari**
Turning off defer support in `main` until the implementation is complete. This will be merged into https://github.com/apollographql/apollo-ios-dev/pull/121 before that PR is merged into `main`.

### CODE REVIEW

**Comment by AnthonyMDev** [comment]
Did you forget to push your commits to the remote branch? This only removes the docs page from the nav bar.

**Comment by calvincestari** [comment]
> Did you forget to push your commits to the remote branch? This only removes the docs page from the nav bar.

Nope, it's simply not done yet

**Comment by AnthonyMDev** [comment]
Okay, no problem. I'm going to convert this to draft in the mean time then.

**Comment by calvincestari** [comment]
Ready for review now with https://github.com/apollographql/apollo-ios-dev/pull/122/commits/4c89d65ea920dfa1a79db1ac87cd77afb51c8a3f.

**Review by AnthonyMDev — APPROVED** [review]

**Comment by calvincestari** [comment]
@infotracktechnology - there is no policy for this specific repo to disallow forking. I believe we have that controlled at the organizational level and all of our OSS repos should allow forking. If you can fork any of the other Apolo OSS repos then you should be able to fork this one too.

**Pull request merged**
