### PR TITLE
Tuist updates

### PR DESCRIPTION
**Pull request by BobaFetters**
Updating to newest tuist version to get multiplatofmr target support, and making a few tweaks to get rid of some warnings in the generated project

Closes apollographql/apollo-ios#3303

### CODE REVIEW

**Comment by calvincestari** [comment]
It looks like the `Run Tuist Generation` test was skipped here. We should definitely have that CI test run right?

**Comment by BobaFetters** [comment]
> It looks like the `Run Tuist Generation` test was skipped here. We should definitely have that CI test run right?

Ah yea didn't think about that since no changes are happening in the Swift code it is skipping the project generation, and I need to bump the version in the CI script

**Comment by BobaFetters** [comment]
Going to add a sample change to a swift file to trigger the jobs and make sure they pass

**Review by AnthonyMDev — APPROVED** [review]
Not sure what's causing those test failures. Where is `NSImage` being used???

But otherwise LGTM

**Comment by BobaFetters** [comment]
Looks like that fixed, going to remove that test change and merge. Also NSImage is used in `URLSessionClientTests`

**Pull request merged**
