### PR TITLE
merge: `feature/defer` branch into `main`

### PR DESCRIPTION
**Pull request by calvincestari**
This is not a complete implementation of the `@defer` directive yet; the feature branch is being merged in now to support the parallel work of configurable field/fragment merging and avoid messy merge conflicts later when the two collide. `@defer` will be disabled until the implementation is complete.

**DO NOT MERGE until https://github.com/apollographql/apollo-ios-dev/pull/122 is merged into this PR.**

### CODE REVIEW

**Review by AnthonyMDev — CHANGES_REQUESTED** [review]
I think we should add in the validation that disallows `defer` usage before we merge this into `main`.

**Comment by AnthonyMDev** [comment]
Oh, just saw you have that PR up!

**Comment by calvincestari** [comment]
> I think we should add in the validation that disallows `defer` usage before we merge this into `main`.

Certainly, that's to be done in https://github.com/apollographql/apollo-ios-dev/pull/122 which is intended to be merged into this PR.

**Comment by calvincestari** [comment]
I'll make this a draft until that pre-merge is done so we can't make a mistake here.

**Review by AnthonyMDev — APPROVED** [review]

**Pull request merged**
